services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka

  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: kafka-1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: kafka-2
    ports:
      - '9093:9092'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka

  kafka-3:
    image: 'bitnami/kafka:latest'
    container_name: kafka-3
    ports:
      - '9094:9092'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka
  
  app-consumer:
    image: node:lts
    container_name: app-consumer
    volumes:
      - ../app-consumer:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm i && npm run start:dev"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka

  app-producer:
    image: node:lts
    container_name: app-producer
    volumes:
      - ../app-producer:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm i && npm run start:dev"
    ports:
      - 3000:3000
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
